GET http://localhost:3000/todos/
###

GET http://localhost:3000/todos/12/ 
###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###

PUT http://localhost:3000/todos/2/
Content-Type: application/json

{ "status": "DONE"}
###

PUT http://localhost:3000/todos/2/
Content-Type: application/json

{ "todo":"Some task" }
###

PUT http://localhost:3000/todos/2/
Content-Type: application/json

{ "priority":"MEDIUM" }
###

DELETE http://localhost:3000/todos/1/ 
###
